# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__
np.show_config()


Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.8
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/g3/pffjr_y96bq06blnkf72x_hw0000gn/T/build-env-3avvq

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_v = np.zeros(10)
null_v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
null_v.size


10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.size)

Return the number of elements along a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which the elements are counted.  By default, give
    the total number of elements.

    .. versionchanged:: 2.4
       Extended to accept multiple axes.

Returns
-------
element_count : int
    Number of elements along the specified axis.

See Also
--------
shape : dimensions of array
ndarray.shape : dimensions of array
ndarray.size : number of elements in array

Examples
--------
>>> import numpy as np
>>> a = np.array([[1,2,3],[4,5,6]])
>>> np.size(a)
6
>>> np.size(a,axis=1)
3
>>> np.size(a,axis=0)
2
>>> np.size(a,axis=(0,1))
6


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10, 50, 1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = np.flip(a, 0)
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a = np.arange(9)
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
b = np.array([1, 2, 0, 0, 4, 0])
b.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
a = np.random.random((3,3,3))
a

array([[[0.83495424, 0.38951229, 0.24089222],
        [0.05974908, 0.87054944, 0.20715782],
        [0.87709189, 0.94075523, 0.17999233]],

       [[0.11595057, 0.18235921, 0.55458959],
        [0.94880158, 0.68410318, 0.60387084],
        [0.56184884, 0.78022433, 0.59039629]],

       [[0.41363875, 0.05197158, 0.78915883],
        [0.97798402, 0.47907982, 0.64136171],
        [0.55767453, 0.14236046, 0.32299217]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
a = np.random.random((10, 10))
a.min(), a.max()

(np.float64(0.018439864936021566), np.float64(0.9943067011735048))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
a = np.random.random((30))
a.mean()

np.float64(0.5544940200988673)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
b = np.pad(a, 1)
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
a = np.eye(5)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
a = np.zeros((8,8))
a[1::2, 1::2] = 1
a[0::2, 0::2] = 1
a


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
np.unravel_index(99, np.array((6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = np.random.random((5,5))
print(a)
a = (a-np.mean(a))/np.std(a)
a

[[0.49348469 0.06200832 0.37915305 0.67258021 0.27563298]
 [0.79182035 0.61490077 0.31969961 0.84648868 0.50378371]
 [0.59575512 0.61884011 0.54145962 0.25452521 0.66606944]
 [0.47679246 0.97427192 0.40641194 0.84948313 0.97399232]
 [0.14522861 0.61302639 0.78068586 0.46331114 0.83713533]]


array([[-0.30176397, -2.09084724, -0.77583125,  0.44084171, -1.20506915],
       [ 0.93526169,  0.20167837, -1.0223503 ,  1.16193968, -0.2590599 ],
       [ 0.12229241,  0.21801256, -0.10283967, -1.29259088,  0.4138453 ],
       [-0.37097699,  1.69178294, -0.66280434,  1.17435593,  1.69062358],
       [-1.74578074,  0.19390639,  0.88909339, -0.42687625,  1.12315672]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

a = np.array([(1,2,3,4)],  dtype=color)
print(a[0]['r'])


a = np.array((1,2,3,4),  dtype=color)
a['r']
# a[0]['r'] errors
# a['r'][0] errors



1


array(1, dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
a = np.random.random((5,3))
b = np.random.random((3,2))


a@b

array([[0.96865532, 1.19354951],
       [0.74367419, 0.75739853],
       [0.34804959, 0.36896041],
       [0.71652691, 0.96895443],
       [0.86936375, 0.98211475]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = np.random.random((5))
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  1. -10.  -1.   7.   3.  -5.  -2.  -4.  -2.  -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.array([1,1])
b = np.array([1,0])

c = np.intersect1d(a, b)
c

array([1])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# no. emath auto converts to complex nums

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [32]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [99]:
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [78]:
a = np.sort(np.random.random((10)))
print(a)


[0.08737992 0.16528066 0.33337402 0.33700316 0.44761932 0.66676732
 0.69019675 0.83469794 0.87205167 0.93073313]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [102]:
A = np.random.randint(0, 1)
B = np.random.randint(0, 1)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B, rtol=0.5)
print(equal)

True


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [79]:
a = np.sort(np.random.random((10)))
a[-1] = 0
a

array([0.01926031, 0.02794241, 0.04956935, 0.23656525, 0.32868247,
       0.36999293, 0.6778097 , 0.73245186, 0.75113819, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [36]:
X = np.random.random((2))
Y = np.random.random((2))

C = 1/np.subtract.outer(X, Y)
C

array([[ 4.57380166,  2.33155185],
       [-8.94272327, 10.15851059]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [86]:
v = np.arange(100)

target = 55.5

v[(np.abs(v - target)).argmin()]

np.int64(55)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import jax.numpy as jnp


 

In [37]:
a = np.random.random((100, 2))


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
a = np.ones((5,3))
print(a)
a = a-a.mean(axis=1, keepdims=True)
a




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [89]:
a = np.random.random((4, 5))

a = a[a[:,3].argsort()]
a

array([[0.01799104, 0.51982652, 0.07815477, 0.16505145, 0.54852667],
       [0.99694864, 0.99260938, 0.08084536, 0.49786219, 0.47408495],
       [0.62824201, 0.64096396, 0.50016606, 0.90430966, 0.0534175 ],
       [0.90601273, 0.4358383 , 0.20200934, 0.98314994, 0.99825463]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [90]:
v = np.arange(100)

target = 55.5

v[(np.abs(v - target)).argmin()]

np.int64(55)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [62]:
a = np.random.randint(0,10,(3,4,3,4))
print(a)
a.sum(axis=(-1, -2))


[[[[2 6 9 1]
   [0 3 1 3]
   [1 3 7 3]]

  [[5 0 3 8]
   [9 7 4 4]
   [8 3 6 8]]

  [[2 0 6 0]
   [6 6 0 8]
   [6 6 7 9]]

  [[3 8 2 2]
   [7 8 3 7]
   [5 3 0 3]]]


 [[[1 7 9 4]
   [3 1 4 2]
   [0 8 9 9]]

  [[9 4 5 3]
   [1 5 8 4]
   [4 5 9 5]]

  [[2 5 0 1]
   [7 8 1 4]
   [3 8 3 4]]

  [[9 0 0 8]
   [9 3 4 6]
   [3 8 6 7]]]


 [[[9 3 9 5]
   [8 7 8 2]
   [7 0 0 1]]

  [[2 4 9 8]
   [5 7 3 3]
   [6 2 4 2]]

  [[6 8 7 8]
   [0 9 1 8]
   [5 1 1 2]]

  [[0 1 8 4]
   [0 3 4 1]
   [0 1 6 2]]]]


array([[39, 65, 56, 51],
       [57, 62, 46, 63],
       [59, 55, 56, 30]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

<class 'tuple'>


In [44]:
a = np.ones((5,5,3))
b = np.ones((5,5))

c = a * b[:,:,None]
print(c)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★)

In [93]:
a = np.random.random((2,2))
print(a)
a[[0, 1]] = a[[1,0]]
a

[[0.24775335 0.40081832]
 [0.59017144 0.40728965]]


array([[0.59017144, 0.40728965],
       [0.24775335, 0.40081832]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [69]:
a = np.ones((16,16))

a = np.add.reduceat(a, (0,4,8,12), 0)

a = np.add.reduceat(a, (0,4,8,12), 1)
a

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [94]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5


print (a[np.argpartition(-a,n)[:n]])

[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [95]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

712 ms ± 31.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
84 ms ± 659 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
100 ms ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)